# -*- coding: utf-8 -*-
"""test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16oNn7T8fQWb48d3p6s8euH_d0Jrfs5bn
"""

from alpha_vantage.timeseries import TimeSeries
import pandas as pd

# Tumhara API key yahan daalo
api_key = "RE8ZRMJYU0LH8FX1"

# Alpha Vantage object create karo
ts = TimeSeries(key=api_key, output_format='pandas')

try:
    # Example: 'RELIANCE.BSE' => BSE (Indian) format
    data, meta_data = ts.get_daily(symbol='RELIANCE.BSE', outputsize='compact')

    # Latest 5 days ka data print karo
    print("\n📊 Last 5 Days Data:\n")
    print(data.head())

except Exception as e:
    print("\n❌ Error fetching data:")
    print(e)